const DATA=window.STAYSCAPE_DATA;
function pageShell(active,content){document.getElementById("app").innerHTML=navbar(active)+content+footer();initNavbar();}

function homePage(){
 const heroImg="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85";
 return `<main>
 <section class="hero"><div class="container hero-grid"><div><div class="eyebrow">DISCOVER · STAY · EXPERIENCE</div><h1>Find your next <span>stay.</span></h1><p class="hero-copy">Beautiful homes, memorable experiences and useful travel services — all in one place.</p><a class="btn btn-dark btn-pill" href="${link("pages/public/homes.html")}">Explore stays</a></div>
 <div class="hero-image"><img src="${heroImg}" alt="Beautiful holiday home"><div class="hero-overlay"><div><b>Coastal Escape</b><small>Goa, India</small></div><b>★ 4.9</b></div></div></div>${searchBar()}</section>
 <div class="container">
  <section class="section"><div class="section-head"><h2>Special offer</h2></div><div class="offer"><div><div class="eyebrow">LIMITED OFFER</div><h2>Welcome to StayScape</h2><p class="muted">Get 15% off your first stay with us.</p><span class="offer-code">STAY15</span></div><a class="btn btn-dark btn-pill" href="${link("pages/public/homes.html")}">Explore stays</a></div></section>
  <section class="section"><div class="section-head"><h2>Explore by category</h2></div><div class="category-grid">${DATA.categories.map(c=>`<a class="category" href="${link("pages/public/homes.html")}?category=${encodeURIComponent(c[1])}"><span class="emoji">${c[0]}</span><small>${c[1]}</small></a>`).join("")}</div></section>
  <section class="section"><div class="section-head"><h2>Popular homes</h2><a class="muted" href="${link("pages/public/homes.html")}">Show all →</a></div><div class="grid">${DATA.properties.slice(0,4).map(propertyCard).join("")}</div></section>
  <section class="section"><div class="section-head"><h2>Things to experience</h2><a class="muted" href="${link("pages/public/experiences.html")}">Show all →</a></div><div class="grid">${DATA.experiences.map(experienceCard).join("")}</div></section>
  <section class="section"><div class="section-head"><h2>Services for your trip</h2><a class="muted" href="${link("pages/public/services.html")}">Show all →</a></div><div class="grid">${DATA.services.map(serviceCard).join("")}</div></section>
 </div></main>`;
}
function listingPage(kind){
 const arr=kind==="homes"?DATA.properties:kind==="experiences"?DATA.experiences:DATA.services;
 const cards=kind==="homes"?arr.map(propertyCard).join(""):kind==="experiences"?arr.map(experienceCard).join(""):arr.map(serviceCard).join("");
 return `<main><div class="container section"><div class="section-head"><div><div class="eyebrow">${kind.toUpperCase()}</div><h1>${kind==="homes"?"Find places to stay":kind==="experiences"?"Find things to do":"Make your trip easier"}</h1></div></div>${searchBar()}<div class="filter-bar"><button class="filter-chip">Location</button><button class="filter-chip">Price</button><button class="filter-chip">Dates</button><button class="filter-chip">Guests</button><button class="filter-chip">Rating</button><button class="filter-chip">More filters</button></div><div class="results-top"><p class="muted">${arr.length} options</p><select class="field" id="sortSelect" style="width:auto"><option>Recommended</option><option>Price low to high</option><option>Price high to low</option><option>Rating</option></select></div><div class="grid" id="listingGrid" style="margin-top:18px">${cards}</div></div></main>`;
}
function detailPage(type,id){
 const x=type==="property"?DATA.properties.find(v=>v.id===id)||DATA.properties[0]:type==="experience"?DATA.experiences.find(v=>v.id===id)||DATA.experiences[0]:DATA.services.find(v=>v.id===id)||DATA.services[0];
 const isP=type==="property";
 return `<main><div class="container detail-hero"><div class="eyebrow">${type.toUpperCase()}</div><h1 class="detail-title">${esc(x.title)}</h1><p class="muted">★ ${x.rating} · ${x.reviews} reviews · ${esc(x.location)}</p>
 <div class="detail-gallery" style="margin-top:22px"><img src="${x.image}" alt=""><img src="${x.image}" alt=""><img src="${x.image}" alt=""><img src="${x.image}" alt=""></div>
 <div class="detail-layout"><article><h2>About this ${type}</h2><p style="margin-top:12px;color:#555;line-height:1.7">${esc(x.description)}</p>
 <div class="stats"><div><b>${isP?x.guests:"Up to 8"}</b><br><small class="muted">${isP?"guests":"guests"}</small></div><div><b>${isP?(x.type):x.duration}</b><br><small class="muted">${isP?"property type":"duration"}</small></div><div><b>English</b><br><small class="muted">language</small></div></div>
 <h2>What this place offers</h2><div class="amenities">${(x.amenities||["Local guidance","Flexible timing","Small groups","Quality service"]).map(a=>`<div class="amenity">✓ ${esc(a)}</div>`).join("")}</div>
 <div class="panel"><h3>${isP?"Your host":"Your host / provider"}</h3><p><b>${esc(x.host||x.provider)}</b></p><p class="muted" style="margin-top:5px">Experienced local partner on StayScape.</p></div>
 <div class="panel"><h3>Reviews</h3><p style="font-size:28px">★ ${x.rating}</p><p class="muted">${x.reviews} reviews</p></div>
 </article>
 <aside><div class="booking-box"><h3>₹${x.price.toLocaleString()} <small class="muted"> ${isP?"night":" / person"}</small></h3><div class="booking-row"><div class="field"><label>${isP?"CHECK-IN":"DATE"}</label><input type="${isP?"date":"date"}" id="bookDate"></div><div class="field"><label>${isP?"CHECK-OUT":"GUESTS"}</label>${isP?'<input type="date" id="bookDate2">':'<input type="number" min="1" value="1" id="bookGuests">'}</div></div><button class="btn btn-dark btn-pill" style="width:100%" id="reserveBtn">Reserve</button><p class="muted" style="font-size:12px;text-align:center;margin-top:10px">You won't be charged yet.</p></div></aside></div></div></main>`;
}
function bookingPage(){
 const id=new URLSearchParams(location.search).get("id")||"p1";const x=DATA.properties.find(v=>v.id===id)||DATA.properties[0];
 return `<main><div class="container section"><div class="eyebrow">RESERVATION</div><h1>Confirm your trip</h1><div class="detail-layout"><div><div class="panel"><h3>Your stay</h3><div class="list-row"><div><b>${esc(x.title)}</b><p class="muted">${x.location}</p></div><b>★ ${x.rating}</b></div></div><div class="panel"><h3>Your dates</h3><div class="booking-row"><div class="field"><label>CHECK-IN</label><input type="date" id="ci"></div><div class="field"><label>CHECK-OUT</label><input type="date" id="co"></div></div><div class="field"><label>GUESTS</label><input type="number" id="guests" value="1" min="1" max="${x.guests}"></div></div><div class="panel"><h3>Guest information</h3><p class="muted">Your logged-in StayScape profile will be used for this reservation.</p></div></div><aside><div class="booking-box"><h3>Price details</h3><div class="list-row"><span>₹${x.price.toLocaleString()} × 1 night</span><b id="basePrice">₹${x.price.toLocaleString()}</b></div><div class="list-row"><span>Service fee</span><span id="serviceFee">₹${Math.round(x.price*.12).toLocaleString()}</span></div><div class="list-row"><b>Total</b><b id="totalPrice">₹${Math.round(x.price*1.12).toLocaleString()}</b></div><button class="btn btn-accent btn-pill" style="width:100%;margin-top:15px" id="payBtn">Continue to payment</button></div></aside></div></div></main>`;
}
function travellerPage(type){
 const u=currentUser()||{name:"Guest"};
 const data={
  dashboard:`<div class="section-head"><div><div class="eyebrow">TRAVELLER</div><h1>Good to see you, ${esc(u.name.split(" ")[0])}</h1><p class="muted">Continue planning your next trip.</p></div></div><div class="stats-grid"><div class="stat"><small>Upcoming trips</small><strong>2</strong></div><div class="stat"><small>Saved places</small><strong>${JSON.parse(localStorage.getItem("ss_wishlist")||"[]").length}</strong></div><div class="stat"><small>Messages</small><strong>3</strong></div><div class="stat"><small>Reviews</small><strong>1</strong></div></div><div class="panel"><h3>Continue planning</h3><div class="grid">${DATA.properties.slice(0,4).map(propertyCard).join("")}</div></div>`,
  profile:`<div class="section-head"><div><div class="eyebrow">PROFILE</div><h1>${esc(u.name)}</h1><p class="muted">${esc(u.email)}</p></div><button class="btn btn-outline">Edit profile</button></div><div class="panel"><h3>About</h3><p class="muted">Tell hosts and travel partners a little about yourself.</p></div>`,
  wishlist:`<div class="section-head"><div><div class="eyebrow">WISHLISTS</div><h1>Saved places</h1></div></div><div class="grid">${(JSON.parse(localStorage.getItem("ss_wishlist")||"[]").map(id=>DATA.properties.find(p=>p.id===id)).filter(Boolean).map(propertyCard).join("")||`<div class="panel" style="grid-column:1/-1"><h3>Your wishlist is empty</h3><p class="muted">Save homes, experiences and services as you explore.</p></div>`)}</div>`,
  trips:`<div class="section-head"><div><div class="eyebrow">TRIPS</div><h1>Your trips</h1></div></div><div class="panel"><h3>Upcoming</h3><div class="list-row"><div><b>Coastal Goa Escape</b><p class="muted">Goa · 3 nights · 2 guests</p></div><span class="btn btn-light">View trip</span></div></div><div class="panel"><h3>Completed</h3><p class="muted">Your completed trips will appear here.</p></div>`,
  notifications:`<div class="section-head"><div><div class="eyebrow">NOTIFICATIONS</div><h1>Updates</h1></div></div><div class="panel">${["Booking confirmed","Your host replied","Trip reminder","Review reminder"].map((n,i)=>`<div class="list-row"><div><b>${n}</b><p class="muted">StayScape notification</p></div><small>${i+1}h ago</small></div>`).join("")}</div>`,
  payments:`<div class="section-head"><div><div class="eyebrow">PAYMENTS</div><h1>Payments & invoices</h1></div></div><div class="panel"><h3>Payment methods</h3><p class="muted">No payment method connected in frontend demo.</p></div><div class="panel"><h3>History</h3><p class="muted">Your transactions will appear here.</p></div>`,
  reviews:`<div class="section-head"><div><div class="eyebrow">REVIEWS</div><h1>Your reviews</h1></div></div><div class="panel"><h3>Cozy Beach House</h3><p>★★★★★</p><p class="muted">Your review content will appear here.</p></div>`,
  settings:`<div class="section-head"><div><div class="eyebrow">SETTINGS</div><h1>Account settings</h1></div></div><div class="panel">${["Personal information","Login & security","Privacy","Notifications","Language & currency"].map(x=>`<div class="list-row"><b>${x}</b><span>›</span></div>`).join("")}</div>`,
  messages:`<div class="section-head"><div><div class="eyebrow">MESSAGES</div><h1>Inbox</h1></div></div><div class="chat-layout"><div class="chat-list"><h3>Conversations</h3>${["Rahul · Cozy Beach House","Arjun · Food Walk","Ananya · Private Chef"].map(x=>`<div class="chat-user">${x}</div>`).join("")}</div><div class="chat-main"><div class="messages" id="messages"><div class="bubble">Hi! How can we help with your trip?</div><div class="bubble me">I'd like to know about check-in.</div></div><div class="chat-input"><input id="chatInput" placeholder="Write a message..."><button class="btn btn-dark" id="sendChat">Send</button></div></div></div>`
 };
 return `<main class="dashboard"><div class="container"><div class="dashboard-nav">${["dashboard","trips","wishlist","messages","notifications","payments","reviews","profile","settings"].map(x=>`<a class="${type===x?"active":""}" href="${link("pages/traveller/"+(x==="dashboard"?"dashboard":x)+".html")}">${x[0].toUpperCase()+x.slice(1)}</a>`).join("")}</div>${data[type]||data.dashboard}</div></main>`;
}
function hostPage(type){
 const content={
 dashboard:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Your hosting dashboard</h1><p class="muted">Manage listings, reservations and earnings.</p></div><a class="btn btn-dark btn-pill" href="${link("pages/host/create-listing.html")}">Create listing</a></div><div class="stats-grid"><div class="stat"><small>Total earnings</small><strong>₹0</strong></div><div class="stat"><small>Reservations</small><strong>0</strong></div><div class="stat"><small>Rating</small><strong>—</strong></div><div class="stat"><small>Active listings</small><strong>0</strong></div></div><div class="panel"><h3>Upcoming reservations</h3><p class="muted">No reservations yet.</p></div>`,
 listings:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Your listings</h1></div><a class="btn btn-dark btn-pill" href="${link("pages/host/create-listing.html")}">+ New listing</a></div><div class="grid">${DATA.properties.slice(0,2).map(propertyCard).join("")}</div>`,
 calendar:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Calendar</h1></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Status</th><th>Price</th></tr></thead><tbody>${["Sep 18","Sep 19","Sep 20","Sep 21","Sep 22"].map((d,i)=>`<tr><td>${d}</td><td>${i===2?"Booked":"Available"}</td><td>₹4,500</td></tr>`).join("")}</tbody></table></div></div>`,
 reservations:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Reservations</h1></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Guest</th><th>Property</th><th>Dates</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr><td>Demo Traveller</td><td>Cozy Beach House</td><td>Sep 18–21</td><td>₹13,500</td><td>Confirmed</td></tr></tbody></table></div></div>`,
 earnings:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Earnings</h1></div></div><div class="stats-grid"><div class="stat"><small>Total</small><strong>₹0</strong></div><div class="stat"><small>This month</small><strong>₹0</strong></div><div class="stat"><small>Upcoming</small><strong>₹0</strong></div><div class="stat"><small>Completed</small><strong>₹0</strong></div></div><div class="panel"><h3>Earnings overview</h3><div style="height:220px;display:grid;place-items:center;color:#777">Chart will connect to real booking data later.</div></div>`,
 analytics:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Analytics</h1></div></div><div class="stats-grid"><div class="stat"><small>Views</small><strong>0</strong></div><div class="stat"><small>Bookings</small><strong>0</strong></div><div class="stat"><small>Occupancy</small><strong>0%</strong></div><div class="stat"><small>Conversion</small><strong>0%</strong></div></div>`,
 messages:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Guest messages</h1></div></div><div class="panel"><div class="list-row"><div><b>Demo Traveller</b><p class="muted">Question about check-in</p></div><button class="btn btn-light">Open</button></div></div>`,
 reviews:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Reviews</h1></div></div><div class="panel"><h3>Cozy Beach House</h3><p>★★★★★</p><p class="muted">4.8 average rating · 24 reviews</p></div>`,
 profile:`<div class="section-head"><div><div class="eyebrow">HOST</div><h1>Host profile</h1></div></div><div class="panel"><h3>Hosting profile</h3><p class="muted">Add your bio, languages and hosting information.</p></div>`
 };
 const side=["dashboard","listings","calendar","reservations","earnings","analytics","messages","reviews","profile"];
 return `<main class="dashboard"><div class="container host-layout"><aside class="side-nav">${side.map(x=>`<a class="${type===x?"active":""}" href="${link("pages/host/"+(x==="dashboard"?"dashboard":x)+".html")}">${x[0].toUpperCase()+x.slice(1)}</a>`).join("")}</aside><section>${content[type]||content.dashboard}</section></div></main>`;
}
function adminPage(type){
 const stats=`<div class="stats-grid"><div class="stat"><small>Users</small><strong>128</strong></div><div class="stat"><small>Hosts</small><strong>42</strong></div><div class="stat"><small>Listings</small><strong>76</strong></div><div class="stat"><small>Bookings</small><strong>214</strong></div></div>`;
 const body={dashboard:`${stats}<div class="panel"><h3>Platform overview</h3><p class="muted">Admin controls for users, hosts, listings, bookings, payments and moderation.</p></div>`,users:`<div class="panel"><h3>Users</h3><div class="table-wrap"><table class="table"><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr>${DATA.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role}</td><td>Active</td></tr>`).join("")}</table></div></div>`,hosts:`<div class="panel"><h3>Hosts</h3><p class="muted">Host verification and management will use backend data later.</p></div>`,properties:`<div class="panel"><h3>Properties</h3><div class="table-wrap"><table class="table"><tr><th>Title</th><th>Host</th><th>Location</th><th>Rating</th><th>Action</th></tr>${DATA.properties.map(p=>`<tr><td>${esc(p.title)}</td><td>${esc(p.host)}</td><td>${esc(p.location)}</td><td>★ ${p.rating}</td><td><button class="btn btn-light">Review</button></td></tr>`).join("")}</table></div></div>`,experiences:`<div class="panel"><h3>Experiences</h3><p class="muted">${DATA.experiences.length} demo experiences.</p></div>`,services:`<div class="panel"><h3>Services</h3><p class="muted">${DATA.services.length} demo services.</p></div>`,bookings:`<div class="panel"><h3>Bookings</h3><p class="muted">Booking moderation and refunds will connect to the backend later.</p></div>`,payments:`<div class="panel"><h3>Payments</h3><p class="muted">Payment records will connect to the payment provider later.</p></div>`,reviews:`<div class="panel"><h3>Reviews moderation</h3><p class="muted">Review reports and moderation tools.</p></div>`,reports:`<div class="panel"><h3>Reports</h3><p class="muted">Reported users, listings and reviews.</p></div>`,analytics:`${stats}<div class="panel"><h3>Platform analytics</h3><div style="height:220px;display:grid;place-items:center;color:#777">Analytics chart placeholder</div></div>`};
 const side=["dashboard","users","hosts","properties","experiences","services","bookings","payments","reviews","reports","analytics"];
 return `<main class="dashboard"><div class="container host-layout"><aside class="side-nav">${side.map(x=>`<a class="${type===x?"active":""}" href="${link("pages/admin/"+x+".html")}">${x[0].toUpperCase()+x.slice(1)}</a>`).join("")}</aside><section><div class="section-head"><div><div class="eyebrow">ADMIN</div><h1>${type[0].toUpperCase()+type.slice(1)}</h1></div></div>${body[type]||body.dashboard}</section></div></main>`;
}
function aiPage(){
 return `<main class="section"><div class="container"><div class="eyebrow">STAYSCAPE AI</div><h1>Plan your trip with AI</h1><p class="muted" style="margin:8px 0 22px">Frontend demo now; real AI API will be connected through Express later.</p><div class="ai-box"><textarea id="aiPrompt" placeholder="Example: Plan a relaxing 3-day trip near Hyderabad under ₹15,000"></textarea><button class="btn btn-dark btn-pill" style="margin-top:12px" id="aiBtn">Create plan</button><div class="ai-result" id="aiResult"></div></div></div></main>`;
}
function initAI(){const b=document.getElementById("aiBtn");if(!b)return;b.onclick=()=>{const p=document.getElementById("aiPrompt").value||"a relaxing trip";document.getElementById("aiResult").innerHTML=`<div class="ai-card"><b>Suggested stay</b><p class="muted">A comfortable stay matched to “${esc(p)}”.</p></div><div class="ai-card"><b>Activities</b><p class="muted">Local food, culture, nature and flexible activities.</p></div><div class="ai-card"><b>Budget</b><p class="muted">Estimated budget will be calculated from real listings once the backend is connected.</p></div>`}}

function protect(){
 const u=currentUser();
 if(!u){location.href=link("pages/auth/login.html?next="+encodeURIComponent(location.pathname));return null}
 return u;
}

document.addEventListener("DOMContentLoaded",()=>{
 const p=document.body.dataset.page;
 if(p==="home"){pageShell("Explore",homePage());initSearch();}
 else if(["homes","experiences","services"].includes(p)){pageShell(p[0].toUpperCase()+p.slice(1),listingPage(p));initSearch();}
 else if(p==="property-details"){pageShell("Homes",detailPage("property",new URLSearchParams(location.search).get("id")));document.getElementById("reserveBtn").onclick=()=>{if(!protect())return;location.href=link("pages/booking/reservation.html?id="+(new URLSearchParams(location.search).get("id")||"p1"))}}
 else if(p==="experience-details"){pageShell("Experiences",detailPage("experience",new URLSearchParams(location.search).get("id")));document.getElementById("reserveBtn").onclick=()=>{if(!protect())return;alert("Experience booking UI ready — payment backend will be connected later.")}}
 else if(p==="service-details"){pageShell("Services",detailPage("service",new URLSearchParams(location.search).get("id")));document.getElementById("reserveBtn").onclick=()=>{if(!protect())return;alert("Service booking UI ready — payment backend will be connected later.")}}
 else if(p==="search-results"){pageShell("Explore",`<main><div class="container section"><div class="eyebrow">SEARCH</div><h1>Search results</h1>${searchBar()}<div class="filter-bar"><button class="filter-chip">Location</button><button class="filter-chip">Price</button><button class="filter-chip">Property type</button><button class="filter-chip">Guests</button><button class="filter-chip">Amenities</button><button class="filter-chip">Rating</button></div><div class="section"><h2>Homes</h2><div class="grid">${DATA.properties.map(propertyCard).join("")}</div><h2 style="margin-top:40px">Experiences</h2><div class="grid">${DATA.experiences.map(experienceCard).join("")}</div><h2 style="margin-top:40px">Services</h2><div class="grid">${DATA.services.map(serviceCard).join("")}</div></div></div></main>`);initSearch();}
 else if(p==="login"||p==="signup"){pageShell("",`<main class="form-page"><form class="form-card" id="authForm"><h1>${p==="login"?"Welcome back":"Create your account"}</h1><p class="muted">${p==="login"?"Log in to continue your trip.":"Join StayScape as a traveller and host."}</p>${p==="signup"?`<div class="form-group"><label>Name</label><input required id="name"></div>`:""}<div class="form-group"><label>Email</label><input type="email" required id="email"></div><div class="form-group"><label>Password</label><input type="password" required id="password"></div><button class="btn btn-dark" type="submit">${p==="login"?"Login":"Create account"}</button><p class="form-note">${p==="login"?`New here? <a href="${link("pages/auth/signup.html")}"><b>Sign up</b></a>`:`Already have an account? <a href="${link("pages/auth/login.html")}"><b>Login</b></a>`}</p><p class="form-note muted">Demo traveller: traveller@stayscape.demo / demo123</p></form></main>`);document.getElementById("authForm").onsubmit=e=>{e.preventDefault();const email=document.getElementById("email").value.trim(),pass=document.getElementById("password").value;let u=DATA.users.find(x=>x.email===email&&x.password===pass);if(p==="signup"){u={id:"u"+Date.now(),name:document.getElementById("name").value,email,password:pass,role:"traveller"};localStorage.setItem("ss_custom_user",JSON.stringify(u))}if(!u){alert("Invalid demo credentials. Use traveller@stayscape.demo / demo123");return}setUser(u);const next=new URLSearchParams(location.search).get("next");location.href=next?next:link("pages/traveller/dashboard.html")}}
 else if(p==="booking"){if(!protect())return;pageShell("Homes",bookingPage());document.getElementById("payBtn").onclick=()=>{const id=new URLSearchParams(location.search).get("id")||"p1";const bookings=JSON.parse(localStorage.getItem("ss_bookings")||"[]");bookings.push({id:"b"+Date.now(),propertyId:id,user:currentUser().id,status:"Confirmed",createdAt:new Date().toISOString()});localStorage.setItem("ss_bookings",JSON.stringify(bookings));location.href=link("pages/booking/confirmation.html?id="+id)}}
 else if(p==="confirmation"){if(!protect())return;const x=DATA.properties.find(v=>v.id===(new URLSearchParams(location.search).get("id")||"p1"))||DATA.properties[0];pageShell("Homes",`<main class="section"><div class="container"><div class="form-card" style="margin:30px auto;text-align:center"><div style="font-size:50px">✓</div><h1>Booking confirmed</h1><p class="muted">Your reservation at ${esc(x.title)} is confirmed.</p><a class="btn btn-dark" style="display:inline-block;margin-top:20px" href="${link("pages/traveller/trips.html")}">View my trips</a></div></div></main>`)}
 else if(p==="ai"){pageShell("Explore",aiPage());initAI();}
 else if(p.startsWith("traveller-")){const type=p.replace("traveller-","");if(!protect())return;pageShell("Explore",travellerPage(type));if(type==="messages"){document.getElementById("sendChat").onclick=()=>{const i=document.getElementById("chatInput"),m=document.getElementById("messages");if(i.value.trim()){m.insertAdjacentHTML("beforeend",`<div class="bubble me">${esc(i.value)}</div>`);i.value=""}}}}
 else if(p.startsWith("host-")){if(!protect())return;const type=p.replace("host-","");pageShell("Explore",hostPage(type))}
 else if(p.startsWith("admin-")){const u=protect();if(!u||u.role!=="admin"){alert("Admin access required.");location.href=link("index.html");return}pageShell("Explore",adminPage(p.replace("admin-","")))}
 else if(p==="create-listing"){if(!protect())return;pageShell("Explore",`<main class="section"><div class="container"><div class="eyebrow">HOST</div><h1>Create your listing</h1><p class="muted" style="margin:8px 0 25px">This multi-step frontend form is ready for backend integration.</p><div class="panel"><div class="form-group"><label>Property type</label><select><option>House</option><option>Apartment</option><option>Villa</option><option>Cabin</option></select></div><div class="form-group"><label>Title</label><input class="field" placeholder="Give your place a title"></div><div class="form-group"><label>Location</label><input class="field" placeholder="City, state, country"></div><div class="form-group"><label>Description</label><textarea class="field" rows="5" placeholder="Describe your place"></textarea></div><div class="form-group"><label>Price per night</label><input class="field" type="number" placeholder="4500"></div><button class="btn btn-dark" onclick="alert('Listing saved as draft in the frontend demo.')">Save draft</button><button class="btn btn-accent" style="margin-left:8px" onclick="alert('Listing published in frontend demo.')">Publish</button></div></div></main>`)}
});